language: cpp
sudo: false

compiler:
  - clang
  - gcc

os:
  - linux

python: 3.6.0

before_install:
  - pip install --user cpp-coveralls
install: true
before_script: true
script: scons
after_success:
  - ./mql.out
  - ls -lart
  - coveralls --gcov-options '\-lp'