language: cpp
dist: trusty
sudo: false

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
before_install:
  - eval "${MATRIX_EVAL}"

install:
  - pip install --user cpp-coveralls

before_script: true

script:
  - scons
  - ./build/mql4dllft
  - ./build/mql4dllft
  - ./build/mql4dllft
  - ./build/mql4dllft
  - ./build/mql4dllft
  - ./build/mql4dllft
  - ./build/mql4dllft
  - ./build/mql4dllft
  - ./build/mql4dllft
  - ./build/mql4dllft

after_success: false

after_failure: false

cache: pip