language: cpp
dist: trusty
sudo: false

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
        sonarcloud:
          organization: "mcqueen256-github"
          token:
            secure: "$SONARCLOUD_KEY"
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
        sonarcloud:
          organization: "mcqueen256-github"
          token:
            secure: "$SONARCLOUD_KEY"
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
        sonarcloud:
          organization: "mcqueen256-github"
          token:
            secure: "$SONARCLOUD_KEY"
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
  - eval "${MATRIX_EVAL}"
  - jdk_switcher use oraclejdk8

install:
  - pip install --user cpp-coveralls

before_script: true

script:
  - build-wrapper-linux-x86-64 --out-dir bw-output scons
  - sonar-scanner

after_success:
  - ./build/mql4dllft
  - coveralls --gcov-options '\-lp'

after_failure:
  - coveralls --gcov-options '\-lp'

#cache:
#  directories:
#    - '$HOME/.sonar/cache'