language: cpp
sudo: false

compiler:
  - clang
  - gcc

os:
  - linux

python: 3.6.0

addons:
  sonarcloud:
    organization: "your_organization_key"
    token:
      secure: "$SONAR_CLOUD_ENCRYPTED_KEY"

before_install:
  - pip install --user cpp-coveralls
install: true
before_script: true
script:
  - scons
  - sonar-scanner
after_success:
  - ./mql.out
  - ls -lart
  - coveralls --gcov-options '\-lp'
cache:
  directories:
    - '$HOME/.sonar/cache'